Give moderators control of the types of posts in their subs
Phuks-co/throat pull request #217
Opened 2020-10-01 17:37 UTC by happy-river

We have some subs that would like to be memes-only and some that would like to be text-only.  Add new sub settings to give moderators finer control over what kinds of posts to allow in their subs.

The Submit a Post form was already problematic because if you navigated to it from the home page and then typed in the name of a sub that allowed polls, you wouldn't see the poll option, and if you navigated to it from a sub that allowed polls and typed in the name of a sub that didn't allow polls, it would allow you to create a poll anyway. Adding more options made this worse, so I redid it to have the JS fetch the types of posts possible for each sub when it fetches the sub name suggestions, and to show and hide the radio buttons accordingly.  The logic for showing and hiding form components based on the selected radio button was duplicated in the template and in the JS, so I simplified the template by making the JS logic run when the form is loaded.

2020-10-01 17:40 UTC, happy-river commented
This PR also modifies the Submit a Post form so that the poll datepicker is only shown when its checkbox is selected.

2020-10-02 02:16 UTC, Polsaker approved these changes
LGTM, will merge after doing some more local testing

2020-10-03 18:57 UTC, Polsaker requested changes
A small issue I found while testing this is that by default all existing subs have all post types disabled, imo we should leave everything enabled by default for existing and new subs

2020-10-03 18:57 UTC, Polsaker commented on app/html/sub/settings.html
> +          <label for="upload_posts" class="pure-checkbox">
The `for` in these label fields is wrong, it should match the name of the field (otherwise clicking the label won't tick the checkbox).

2020-10-03 21:58 UTC, happy-river commented
> A small issue I found while testing this is that by default all existing subs have all post types disabled, imo we should leave everything enabled by default for existing and new subs

Did you run the migration?

2020-10-03 22:08 UTC, Polsaker commented
D'oh

2020-10-04 03:58 UTC, merged